version: "3.8"

volumes:
  db_data:
  redis_data:
  nextcloud_data:
  onlyoffice_data:

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: supersecret   # TROQUE
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: ["redis-server","--save","","--appendonly","no"]
    volumes:
      - redis_data:/data

  nextcloud:
    image: nextcloud:29-apache
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: supersecret   # MESMA de cima
      REDIS_HOST: redis
      PHP_UPLOAD_LIMIT: 1024M
      PHP_MEMORY_LIMIT: 1024M
      # NEXTCLOUD_TRUSTED_DOMAINS: cloud.drg.ink
      # OVERWRITEHOST: cloud.drg.ink
      # OVERWRITEPROTOCOL: https
    volumes:
      - nextcloud_data:/var/www/html


  onlyoffice:
    image: onlyoffice/documentserver:latest
    environment:
      JWT_ENABLED: "true"
      JWT_SECRET: "mude_esta_chave_grande_e_secreta"  # USE a mesma no app do Nextcloud
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data

